# Generated by Django 5.2.8 on 2025-11-17 12:19

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_vector_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('journal', 'Journal'), ('reminders', 'Reminders')], default='journal', max_length=10)),
                ('entry', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('logs', 'Captains Logs'), ('health', 'Health'), ('work', 'Work'), ('holiday', 'Holiday'), ('family', 'Family')], default='logs', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminder_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('unsent', 'Unsent'), ('sent', 'Sent')], default='unsent', max_length=10, null=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
