# Generated by Django 5.2.10 on 2026-02-15 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='category',
        ),
    ]
