# Generated by Django 5.2.10 on 2026-08-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='entry',
            field=models.TextField(max_length=5000),
        ),
    ]
