"""
Django settings for CS50w_final_project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
import sentry_sdk

import dj_database_url

from dotenv import load_dotenv
load_dotenv()


from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY") 

# OpenAI API
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

DEBUG = os.getenv('DEBUG', 'False') == 'True'  # False on Heroku, True locally


# Security settings for production
SECURE_SSL_REDIRECT = not DEBUG  # Force HTTPS in production
SESSION_COOKIE_SECURE = not DEBUG  # Secure session cookies
CSRF_COOKIE_SECURE = not DEBUG  # Secure CSRF cookies
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


HEROKU_APP_HOST = os.getenv("HEROKU_APP_HOST")  # e.g. "heydayta-12345e6789ab.herokuapp.com"
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "heydayta.app", "www.heydayta.app"]
if HEROKU_APP_HOST:
    ALLOWED_HOSTS.append(HEROKU_APP_HOST)
    ALLOWED_HOSTS.append(".herokuapp.com")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'rest_framework',
    'apps.accounts',
    'apps.api',
    'corsheaders',
]
# Enables both regular login and allauth social login
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'CS50w_final_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'build'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # `allauth` needs this from django
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'CS50w_final_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # Default database settings for local development.
    # These values come from your local .env file and point to your own Postgres instance.
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DATABASE_NAME'),
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# On Heroku, the Postgres add-on exposes the connection string in the DATABASE_URL
# environment variable. When this variable is present, override the local settings
# above and use the Heroku database instead.
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    # dj_database_url.parse turns the URL string into the dict format that Django expects
    # for DATABASES['default']. conn_max_age enables persistent connections, and
    # ssl_require=True makes sure the connection to Heroku Postgres uses SSL.
    DATABASES['default'] = dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

SITE_ID = 1


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'frontend' / 'build' / 'static']

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# update the AUTH_USER_MODEL setting so instead of using the default user model, to use the custom User model.
AUTH_USER_MODEL = 'accounts.User' 

# default authentication classes in Django DRF specifies the authentication methods that the APIs will use. 
# Anytime we try to authenticate the user in a viewset in our endpoint, we will utilize this method of authentication. 
# It will hook into the Django sessionauthentication service. 
# We can determine which user is trying to access the resource and allow access.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID'),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET'),
        }
    }
}

# it allows React to communicate with Django
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://heydayta-590c2392dfd2.herokuapp.com",
    "https://www.heydayta.app",
    "https://heydayta.app",
]
CORS_ALLOW_CREDENTIALS = True

# Celery settings
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# SSL config ONLY for Heroku Redis (production)
if os.getenv('ENVIRONMENT') != 'development':
    CELERY_BROKER_USE_SSL = {
        'ssl_cert_reqs': None
    }


# Django EMAIL settings
# Development: print emails to console (instant!)
# Production: use Gmail SMTP (real emails)
if os.getenv('ENVIRONMENT') == 'development':
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Django EMAIL settings (production-ready)
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.mail.ovh.net")
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 465))
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "False") == "True"
    EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "True") == "True"
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
    DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)


sentry_sdk.init(
    dsn=os.getenv("SENTRY_DSN"),
    environment="production" if not DEBUG else "development",
)